language: node_js
node_js:
  - "10"
cache: yarn
script:
  - make
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  on:
    branch: master
