language: node_js
node_js:
  - "10"
cache: yarn
before_script:
  - export TZ=Australia/Melbourne
script:
  - make
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  fqdn: boss.51dianxiaoge.com
  on:
    branch: master
